### ISSUE TITLE
Display pandas dataframe as a table

### ISSUE THREAD

**Issue by marketneutral** [QuantStack/voila-vuetify#12] opened 2019-08-01 20:15 UTC
This is a fantastic project! It really fills a critical hole in the ecosystem. Thank you for all the work so far.

I would like to display a pandas dataframe either as a SlickGrid, QGrid, or a Vuetify`v-data-table`. Could you please provide an example of how to do that?

**Comment by mariobuikhuizen** [comment] 2019-08-01 21:44
Thanks!

I'm not familiar with SlickGrid or QGrid, so I've made an example using ipyvuetify. Because the `v-data-table` uses a v-slot feature not supported by the regular ipyvuetify widgets, the [template widget](https://github.com/mariobuikhuizen/ipyvuetify#alternate-usage) is used in this example.

```python
import ipyvuetify as v
from traitlets import (Unicode, List)
import pandas as pd

df = pd.DataFrame([['Tom', 10], ['Nick', 15], ['Juli', 14]], columns = ['Name', 'Age'])
df

class MyDataTable(v.VuetifyTemplate):
    headers = List([
        {'text': 'Name', 'sortable':  False, 'value': 'Name'},
        {'text': 'Age', 'value': 'Age', 'align': 'right'}
    ]).tag(sync=True)

    items = List(df.to_dict(orient='records')).tag(sync=True)

    template = Unicode('''
        <v-data-table
            :headers="headers"
            :items="items"
            class="elevation-1"
        >
            <template v-slot:items="props">
                <td>{{ props.item.Name }}</td>
                <td class="text-xs-right">{{ props.item.Age }}</td>
            </template>
        </v-data-table>
    ''').tag(sync=True)

MyDataTable()
```
<img width="954" alt="Schermafbeelding 2019-08-01 om 23 43 42" src="https://user-images.githubusercontent.com/46192475/62329474-423f4100-b4b6-11e9-82b8-793a3c2832bf.png">

**Comment by marketneutral** [comment] 2019-08-02 12:39
Wow, that's great. Thank you and thanks for the quick reply. I wanted to make this more dynamic (so you don't have to hardcode the column names in the strings) and I came up with this:

```python
df = pd.DataFrame(
    [['Tom', 'Jones', 10], ['Nick', 'Jonas', 15], ['Juli', 'Jewel', 14]],
    columns = ['First', 'Last', 'Age']
)

class MyDataTable(v.VuetifyTemplate):
    columns = []
    v_slot = '<template v-slot:items="props">'
    for i, colname in enumerate(df.columns):
        if i == 0:
            list_item = {'text': colname, 'sortable': False, 'value': colname}
            v_slot = v_slot + f'<td>{{{{props.item.{colname}}}}}</td>'
        else:
            list_item = {'text': colname, 'value': colname, 'align': 'right'}
            v_slot = v_slot + f'<td class="text-xs-right">{{{{props.item.{colname}}}}}</td>'
        columns.append(list_item)
    v_slot = v_slot + '</template>'

    headers = List(columns).tag(sync=True)
    items = List(df.to_dict(orient='records')).tag(sync=True)
    template = Unicode(
        '<v-data-table :headers="headers" :items="items" class="elevation-1">' \
        + v_slot \
        + '</v-data-table>'
    ).tag(sync=True)

MyDataTable()
```
![image](https://user-images.githubusercontent.com/16124573/62370066-7ee35a80-b4ff-11e9-93dd-7dfbf37160b1.png)

I'm interested to work on this some more (or cede to a proper developer 😀). I'd like to instantiate it with passing in the dataframe and some config params on the columns. I tried the following but I get nothing back (no error, just nothing):

```python
class MyDataTable(v.VuetifyTemplate):
    def __init__(self, df):
        super().__init__()
        columns = []
        v_slot = '<template v-slot:items="props">'
        for i, colname in enumerate(df.columns):
            if i == 0:
                list_item = {'text': colname, 'sortable': False, 'value': colname}
                v_slot = v_slot + f'<td>{{{{props.item.{colname}}}}}</td>'
            else:
                list_item = {'text': colname, 'value': colname, 'align': 'right'}
                v_slot = v_slot + f'<td class="text-xs-right">{{{{props.item.{colname}}}}}</td>'
            columns.append(list_item)
        v_slot = v_slot + '</template>'

        self._headers = List(columns).tag(sync=True)
        self._items = List(df.to_dict(orient='records')).tag(sync=True)
        self._template = Unicode(
            '<v-data-table :headers="headers" :items="items" class="elevation-1">' \
            + v_slot \
            + '</v-data-table>'
        ).tag(sync=True)

    @property
    def headers():
        return self._headers
    
    @property
    def items():
        return self._items
    
    @property
    def template():
        return self._template

MyDataTable(df)
```

Do you have any guidance and/or suggestions on this?

**Comment by mariobuikhuizen** [comment] 2019-08-06 13:36
(1) Thanks for reporting this issue. This is now fixed ipyvuetify 0.1.10 (no need to update, in this situation the newest version is downloaded from CDN).

(1b) The ipyvuetify DataTable widget is the python wrapper around vuetify's v-data-table. Because of the missing v-slot features it's not usable right now. This widget is still included because all wrappers are auto generated. The VuetifyTemplate was used as a workaround. 

(2) Traitlets should not be handled as properties. Also, traitlets starting with an underscore are ignored by ipyvuetify.
```python
class MyDataTable(v.VuetifyTemplate):
    
    headers = List().tag(sync=True)
    items = List().tag(sync=True)
    template = Unicode().tag(sync=True)
    
    def __init__(self, df):
        super().__init__()
        columns = []
        v_slot = '<template v-slot:items="props">'
        for i, colname in enumerate(df.columns):
            if i == 0:
                list_item = {'text': colname, 'sortable': False, 'value': colname}
                v_slot = v_slot + f'<td>{{{{props.item.{colname}}}}}</td>'
            else:
                list_item = {'text': colname, 'value': colname, 'align': 'right'}
                v_slot = v_slot + f'<td class="text-xs-right">{{{{props.item.{colname}}}}}</td>'
            columns.append(list_item)
        v_slot = v_slot + '</template>'

        self.headers = columns
        self.items = df.to_dict(orient='records')
        self.template = '<v-data-table :headers="headers" :items="items" class="elevation-1">' \
            + v_slot \
            + '</v-data-table>'

MyDataTable(df)
```

**Comment by maartenbreddels** [comment] 2019-08-07 11:17
> This is a fantastic project! It really fills a critical hole in the ecosystem. Thank you for all the work so far.

Totally agree, but I'm biased :)


I'm assuming the issue is resolved, if you disagree, please re-open.

**Closed by maartenbreddels** 2019-08-07 11:17 UTC

**Comment by snakers4** [comment] 2020-01-31 12:45
Hi!

Sorry for posting in an old issue, but is there any method of updating values in the table once the `viola` page has rendered?

I.e. my use case is - I load an empty table and then after user does something I populate it.

**Comment by minhhoang1023** [comment] 2022-03-18 06:55
Hello, I would like to capture the rendered table as a ipywidgets Output, and then display it. Any idea on how to do this?

**Comment by maartenbreddels** [comment] 2022-03-18 07:51
> Hello, I would like to capture the rendered table as a ipywidgets Output, and then display it. Any idea on how to do this?

I wouldn't do that, it is always better to keep the widget tree intact, so attach it as child to a parent container (e.g. v.Card )

**Comment by maartenbreddels** [comment] 2022-03-22 08:39
> I.e. my use case is - I load an empty table and then after user does something I populate it.

you can put the code from the constructor in a method so it can update right?

I think long term we want to support rendering dataframes in a new project we're working on.

**Comment by samiit** [comment] 2023-01-11 12:57
> 

And which project would that be?

**Comment by maartenbreddels** [comment] 2023-01-11 13:05
Solara, it's still in progress, but if you cannot wait, you can take a look at https://solara.dev/api/dataframe

**Comment by samiit** [comment] 2023-01-11 13:23
Thanks for responding Maarten.

I was checking Solara for some time but not enough to use it. I wanted to confirm whether a simple ipyvuetify WebApp can in someway be served using FastAPI - using SOLARA? Can you please direct me to the right place?

**Comment by maartenbreddels** [comment] 2023-01-11 13:48
Yes, that's exactly what it does. 'classic' widget support is not that well tested, we write most of our apps using the react-like components. We should document that workflow, but I'll give you a private tutorial :)

Put the following in mysolaratest.py

```python
import ipyvuetify as v
import pandas as pd
from traitlets import List, Unicode

df = pd.DataFrame([["Tom", 12], ["Nick", 15], ["Juli", 14]], columns=["Name", "Age"])
df


class MyDataTable(v.VuetifyTemplate):
    headers = List(
        [
            {"text": "Name", "sortable": False, "value": "Name"},
            {"text": "Age", "value": "Age", "align": "right"},
        ]
    ).tag(sync=True)

    items = List(df.to_dict(orient="records")).tag(sync=True)

    template = Unicode(
        """
        <v-data-table
            :headers="headers"
            :items="items"
            class="elevation-1"
        >
            <template v-slot:items="props">
                <td>{{ props.item.Name }}</td>
                <td class="text-xs-right">{{ props.item.Age }}</td>
            </template>
        </v-data-table>
    """
    ).tag(sync=True)


widget = MyDataTable()
```

Now run `solara run mysolaratest.py:widget` where the name after the `:` is the widget name. 

If you edit the file, and save it, it should also auto reload.

**Comment by samiit** [comment] 2023-01-12 07:21
Thank you so much @maartenbreddels 

I will try it out from FastAPI right away and give feedback.

**Comment by samiit** [comment] 2023-01-13 08:21
Hi @maartenbreddels 
I understand it is a Solara question, but I am not able to run the command you gave. The following is the error with solara-1.0.3

In short: a circular import

Any hints to solve it now?

```
(venv) (base) sam@sam-Aspire-E5-575G:~/Projects/Learning/Python/WebApps/FastAPI/FastAPI_Solara/solara$ solara run datatable.py:widget
Solara server is starting at http://localhost:8765
Traceback (most recent call last):
  File "/home/sam/Projects/Learning/Python/WebApps/FastAPI/FastAPI_Solara/venv/bin/solara", line 8, in <module>
    sys.exit(main())
  File "/home/sam/Projects/Learning/Python/WebApps/FastAPI/FastAPI_Solara/venv/lib/python3.9/site-packages/solara/__main__.py", line 606, in main
    cli()
  File "/home/sam/Projects/Learning/Python/WebApps/FastAPI/FastAPI_Solara/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/sam/Projects/Learning/Python/WebApps/FastAPI/FastAPI_Solara/venv/lib/python3.9/site-packages/rich_click/rich_group.py", line 21, in main
    rv = super().main(*args, standalone_mode=False, **kwargs)
  File "/home/sam/Projects/Learning/Python/WebApps/FastAPI/FastAPI_Solara/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/sam/Projects/Learning/Python/WebApps/FastAPI/FastAPI_Solara/venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sam/Projects/Learning/Python/WebApps/FastAPI/FastAPI_Solara/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sam/Projects/Learning/Python/WebApps/FastAPI/FastAPI_Solara/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/sam/Projects/Learning/Python/WebApps/FastAPI/FastAPI_Solara/venv/lib/python3.9/site-packages/solara/__main__.py", line 352, in run
    start_server()
  File "/home/sam/Projects/Learning/Python/WebApps/FastAPI/FastAPI_Solara/venv/lib/python3.9/site-packages/solara/__main__.py", line 334, in start_server
    server.run()
  File "/home/sam/Projects/Learning/Python/WebApps/FastAPI/FastAPI_Solara/venv/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/sam/anaconda3/envs/fastapi/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/sam/anaconda3/envs/fastapi/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/sam/Projects/Learning/Python/WebApps/FastAPI/FastAPI_Solara/venv/lib/python3.9/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/sam/Projects/Learning/Python/WebApps/FastAPI/FastAPI_Solara/venv/lib/python3.9/site-packages/uvicorn/config.py", line 477, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/sam/Projects/Learning/Python/WebApps/FastAPI/FastAPI_Solara/venv/lib/python3.9/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/sam/Projects/Learning/Python/WebApps/FastAPI/FastAPI_Solara/venv/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/sam/anaconda3/envs/fastapi/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/sam/Projects/Learning/Python/WebApps/FastAPI/FastAPI_Solara/venv/lib/python3.9/site-packages/solara/server/starlette.py", line 24, in <module>
    from . import app as appmod
  File "/home/sam/Projects/Learning/Python/WebApps/FastAPI/FastAPI_Solara/venv/lib/python3.9/site-packages/solara/server/app.py", line 258, in <module>
    apps["__default__"] = AppScript(os.environ.get("SOLARA_APP", "solara.website.pages:Page"))
  File "/home/sam/Projects/Learning/Python/WebApps/FastAPI/FastAPI_Solara/venv/lib/python3.9/site-packages/solara/server/app.py", line 65, in __init__
    app = self._execute()
  File "/home/sam/Projects/Learning/Python/WebApps/FastAPI/FastAPI_Solara/venv/lib/python3.9/site-packages/solara/server/app.py", line 88, in _execute
    exec(ast, local_scope)
  File "datatable.py", line 35, in <module>
    widget = MyDataTable()
  File "/home/sam/Projects/Learning/Python/WebApps/FastAPI/FastAPI_Solara/venv/lib/python3.9/site-packages/ipyvue/VueTemplateWidget.py", line 146, in __init__
    super().__init__(*args, **kwargs)
  File "/home/sam/Projects/Learning/Python/WebApps/FastAPI/FastAPI_Solara/venv/lib/python3.9/site-packages/ipywidgets/widgets/widget.py", line 480, in __init__
    self.open()
  File "/home/sam/Projects/Learning/Python/WebApps/FastAPI/FastAPI_Solara/venv/lib/python3.9/site-packages/ipywidgets/widgets/widget.py", line 493, in open
    state, buffer_paths, buffers = _remove_buffers(self.get_state())
  File "/home/sam/Projects/Learning/Python/WebApps/FastAPI/FastAPI_Solara/venv/lib/python3.9/site-packages/ipywidgets/widgets/widget.py", line 583, in get_state
    value = to_json(getattr(self, k), self)
  File "/home/sam/Projects/Learning/Python/WebApps/FastAPI/FastAPI_Solara/venv/lib/python3.9/site-packages/traitlets/traitlets.py", line 703, in __get__
    return self.get(obj, cls)
  File "/home/sam/Projects/Learning/Python/WebApps/FastAPI/FastAPI_Solara/venv/lib/python3.9/site-packages/traitlets/traitlets.py", line 659, in get
    default = obj.trait_defaults(self.name)
  File "/home/sam/Projects/Learning/Python/WebApps/FastAPI/FastAPI_Solara/venv/lib/python3.9/site-packages/traitlets/traitlets.py", line 1872, in trait_defaults
    return self._get_trait_default_generator(names[0])(self)
  File "/home/sam/Projects/Learning/Python/WebApps/FastAPI/FastAPI_Solara/venv/lib/python3.9/site-packages/traitlets/traitlets.py", line 627, in default
    return self.make_dynamic_default()
  File "/home/sam/Projects/Learning/Python/WebApps/FastAPI/FastAPI_Solara/venv/lib/python3.9/site-packages/ipywidgets/widgets/trait_types.py", line 168, in make_dynamic_default
    return self.klass(*(self.default_args or ()),
  File "/home/sam/Projects/Learning/Python/WebApps/FastAPI/FastAPI_Solara/venv/lib/python3.9/site-packages/ipywidgets/widgets/widget.py", line 480, in __init__
    self.open()
  File "/home/sam/Projects/Learning/Python/WebApps/FastAPI/FastAPI_Solara/venv/lib/python3.9/site-packages/ipywidgets/widgets/widget.py", line 503, in open
    self.comm = Comm(**args)
  File "/home/sam/Projects/Learning/Python/WebApps/FastAPI/FastAPI_Solara/venv/lib/python3.9/site-packages/ipykernel/comm/comm.py", line 80, in __init__
    BaseComm.__init__(
  File "/home/sam/Projects/Learning/Python/WebApps/FastAPI/FastAPI_Solara/venv/lib/python3.9/site-packages/comm/base_comm.py", line 56, in __init__
    self.open(data=data, metadata=metadata, buffers=buffers)
  File "/home/sam/Projects/Learning/Python/WebApps/FastAPI/FastAPI_Solara/venv/lib/python3.9/site-packages/comm/base_comm.py", line 74, in open
    comm_manager = comm.get_comm_manager()
  File "/home/sam/Projects/Learning/Python/WebApps/FastAPI/FastAPI_Solara/venv/lib/python3.9/site-packages/solara/server/kernel.py", line 48, in get_comm_manager
    from .app import get_current_context
ImportError: cannot import name 'get_current_context' from partially initialized module 'solara.server.app' (most likely due to a circular import) (/home/sam/Projects/Learning/Python/WebApps/FastAPI/FastAPI_Solara/venv/lib/python3.9/site-packages/solara/server/app.py)
(venv) (base) sam@sam-Aspire-E5-575G:~/Projects/Learning/Python/WebApps/FastAPI/FastAPI_Solara/solara$ ^C
(venv) (base) sam@sam-Aspire-E5-575G:~/Projects/Learning/Python/WebApps/FastAPI/FastAPI_Solara/solara$ ipython
Python 3.9.13 (main, Aug 25 2022, 23:26:10) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.8.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import solara

In [2]: solara.__version__
Out[2]: '1.0.3'

In [3]: 

```

**Comment by samiit** [comment] 2023-01-13 08:24
Just as a feedback, I don't get any error and am able to run the command while doing 

```pip install solara==0.19.1```

**Comment by maartenbreddels** [comment] 2023-01-13 12:12
Ah, great you found your way to https://github.com/widgetti/solara/issues/26 !

**Comment by samiit** [comment] 2023-01-13 12:12
That was also circular!

**Comment by samiit** [comment] 2023-01-13 12:13
Thanks for bearing with me @maartenbreddels

**Comment by maartenbreddels** [comment] 2023-01-13 12:16
Your question was a good motivation for me to add a (although minimal) tutorial for people coming from ipywidgets: https://solara.dev/docs/tutorial/ipywidgets
